### ISSUE TITLE
unmet peer dependency with latest version of eslint

### ISSUE THREAD

**Issue by cthorner** [CodingZeal/eslint-config-zeal#66]
I am not able to upgrade to latest version of eslint(v4.1.1) since this package requires a 3.19.x version of eslint. Seems a bit specific. The recommendation on the eslint site is to use Major version and up for peer dependency on eslint(http://eslint.org/docs/developer-guide/shareable-configs#publishing-a-shareable-config).

**Comment by randycoulman** [comment]
I hadn't seen that recommendation before; it wasn't there when we first published this config.  We'll address that when we can.  Thanks for pointing that out!

We haven't yet updated this config for the 4.x series, though it's on our list to get to as soon as we can.

In the mean time, the peer dependency will give you a warning, but I don't believe it will stop you from using ESLint 4.x.

We always set our version spec to be at least the version of eslint for which we've configured all of the rules; using an older version will result in warnings about unknown rule definitions.  Using newer versions is generally safe, though there won't be configurations for any new rules.  Using a newer major version is potentially risky depending on the nature of the breaking changes that caused the major version to change.

**Comment by cthorner** [comment]
Thanks for following up, @randycoulman. I was having issues with my npm-shrinkwrap not getting updated because of the unmet peer dependency. I'm sure there is a way to override it, I just can't figure out how. I'll post back if I find a resolution.

**Comment by cthorner** [comment]
This PR fixed my issues with npm-shrinkwrap and my 2 day bout with dependency hell has come to an end. 💯 All for upgrading webpack. :)
